
networks:
  app:
    external: true
    name: "flux-network"

services:
  steering:
    image: steering-control
    build:
      context: .
      dockerfile: ./steering/Dockerfile
    privileged: true
    environment:
      MQTT_BROKER: "mqtt://mqtt-broker:1883"
      CONFIGURATION: |
        {
          "neutral_position":  60,
          "max_right_position": 70,
          "max_left_position": 52,
          "pin":  15,
          "frequency": 400,
          "topic": "neurons/test-steering/out"
        }
    networks:
      app:

  forward:
    image: forward-control
    build:
      context: .
      dockerfile: ./forward/Dockerfile
    privileged: true
    environment:
      LOG_LEVEL: "debug"
      MQTT_BROKER: "mqtt://mqtt-broker:1883"
      CONFIGURATION: |
        {
          "full_forward":  55,
          "full_backward": 49,
          "full_stop": 53,
          "pin":  32,
          "frequency": 400,
          "topic": "neurons/test-forward/out"
        }
    networks:
      app:
