
networks:
  app:
    external: true
    name: "flux-network"

services:
  steering:
    image: steering-control
    build:
      context: .
      dockerfile: ./steering/Dockerfile
    privileged: true
    environment:
      MQTT_BROKER: "mqtt://mqtt-broker:1883"
      CONFIGURATION: |
        {
          "neutral_position":  60,
          "max_right_position": 70,
          "max_left_position": 50,
          "pin":  15,
          "frequency": 400,
          "topic": "neurons/test-steering/out"
        }
    networks:
      app:
